# Generated by Django 5.2.6 on 2025-12-04 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название_группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата_создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата_обновления')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'group_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='руководитель_группы')),
                ('workers', models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'worker'}, related_name='work_groups', to=settings.AUTH_USER_MODEL, verbose_name='работники')),
            ],
            options={
                'verbose_name': 'рабочая_группа',
                'verbose_name_plural': 'рабочие_группы',
            },
        ),
    ]
