# Generated by Django 5.2.6 on 2025-12-04 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workergroup',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'group_manager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='руководитель_группы'),
        ),
    ]
