# Generated by Django 5.2.6 on 2025-12-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("tickets", "0003_alter_ticket_group"),
        ("users", "0003_alter_workergroup_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="company.organization",
                verbose_name="организация",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="почта"
            ),
        ),
        migrations.DeleteModel(
            name="WorkerGroup",
        ),
    ]
