# Generated by Django 5.2.6 on 2025-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_organization_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('main_manager', 'директор'), ('group_manager', 'руководитель_группы'), ('worker', 'работник')], default='worker', max_length=100, verbose_name='роль'),
        ),
    ]
