# Generated by Django 5.2.6 on 2025-12-05 18:09

import django.db.models.deletion
import sorl.thumbnail.fields
import tickets.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_workergroup_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('status', models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], default='open', verbose_name='статус')),
                ('priority', models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий'), ('critical', 'критический')], default='medium', verbose_name='приоритет')),
                ('photo_before', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=tickets.utils.get_photo_before_path, verbose_name='фото_до')),
                ('photo_after', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=tickets.utils.get_photo_after_path, verbose_name='фото_после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата_создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата_обновления')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.workergroup', verbose_name='рабочая_группа')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
