# Generated by Django 5.2.6 on 2025-12-05 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], verbose_name='из_статуса')),
                ('to_status', models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], verbose_name='в_статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='время_изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tickets.ticket', verbose_name='заявка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история_изменения_статуса',
                'verbose_name_plural': 'истории_изменений_статусов',
            },
        ),
    ]
