# Generated by Django 5.2.6 on 2025-12-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("tickets", "0002_statuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="company.workergroup",
                verbose_name="рабочая_группа",
            ),
        ),
    ]
