# Generated by Django 5.2.6 on 2025-12-15 21:31

import sorl.thumbnail.fields
import tickets.utils
import tickets.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="photo_after",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=tickets.utils.get_photo_after_path,
                validators=[
                    tickets.validators.FileValidator(max_size=10485760)
                ],
                verbose_name="фото_после",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="photo_before",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=tickets.utils.get_photo_before_path,
                validators=[
                    tickets.validators.FileValidator(max_size=10485760)
                ],
                verbose_name="фото_до",
            ),
        ),
    ]
