# Generated by Django 5.2.6 on 2025-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_photo_after_alter_ticket_photo_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='from_status',
            field=models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], max_length=100, verbose_name='из_статуса'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='to_status',
            field=models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], max_length=100, verbose_name='в_статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий'), ('critical', 'критический')], default='medium', max_length=100, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в_работе'), ('closed', 'закрыта'), ('cancelled', 'отменена')], default='open', max_length=100, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
