# Generated by Django 5.2.6 on 2025-12-15 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название_организации'),
        ),
        migrations.AlterField(
            model_name='workergroup',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'group_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='руководитель_группы'),
        ),
        migrations.AlterField(
            model_name='workergroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название_группы'),
        ),
    ]
