# Generated by Django 5.2.6 on 2025-12-16 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_organization_name_alter_workergroup_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workergroup',
            name='workers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('profile__role', 'worker'), ('profile__role', 'group_manager'), _connector='OR'), related_name='work_groups', to=settings.AUTH_USER_MODEL, verbose_name='работники'),
        ),
    ]
