# Generated by Django 5.2.6 on 2025-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_workergroup_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название_организации'),
        ),
    ]
